name: hello-admin-ui

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.7"
      - name: Build Hello Admin UI
        run: |
          yarn install
          yarn run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.OSS_KEY_ID }}
          accessKeySecret: ${{ secrets.OSS_KEY_SECRET }}
          bucket: ${{ secrets.OSS_HELLOADMIN_BUCKET }}
          # e.g. "oss-cn-shanghai.aliyuncs.com"
          endpoint: oss-cn-shanghai.aliyuncs.com
          folder: ./dist
